import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service – AstraMap",
};

export default function TermsPage() {
  return (
    <main className="mx-auto max-w-2xl px-6 py-12 text-stone-800">
      <div className="mb-8">
        <Link
          href="/"
          className="text-sm text-stone-500 transition-colors hover:text-stone-800"
        >
          ← Back to AstraMap
        </Link>
      </div>

      <h1 className="mb-2 text-3xl font-semibold tracking-tight text-stone-900">
        Terms of Service
      </h1>
      <p className="mb-8 text-sm text-stone-500">Effective date: April 6, 2025</p>

      <div className="prose prose-stone max-w-none space-y-8 text-sm leading-relaxed">
        <section>
          <h2 className="mb-3 text-lg font-semibold text-stone-900">1. Acceptance of Terms</h2>
          <p>
            By accessing or using AstraMap (<strong>https://www.astramap.app</strong>),
            you agree to be bound by these Terms of Service. If you do not agree, please
            do not use the service.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-stone-900">2. Description of Service</h2>
          <p>
            AstraMap is an AI-assisted astrology workspace that generates natal charts
            and interpretations based on birth data you provide. The service is intended
            for personal, non-commercial use.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-stone-900">3. Entertainment Purposes Only</h2>
          <p>
            Astrology content generated by AstraMap is provided <strong>for
            entertainment and personal reflection purposes only</strong>. It does not
            constitute medical, psychological, financial, legal, or any other
            professional advice. Do not make important life decisions based solely on
            astrological interpretations.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-stone-900">4. User Accounts</h2>
          <p>
            You must sign in with a valid Google account to use AstraMap. You are
            responsible for all activity that occurs under your account. You agree not to
            share your account credentials with others.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-stone-900">5. Acceptable Use</h2>
          <p className="mb-2">You agree not to:</p>
          <ul className="ml-4 list-disc space-y-1.5 text-stone-700">
            <li>Use the service for any unlawful purpose.</li>
            <li>Attempt to gain unauthorized access to our systems or other users' data.</li>
            <li>Abuse or overload the service (e.g., automated scraping or bulk API calls).</li>
            <li>Upload or enter content that is offensive, harmful, or violates any applicable law.</li>
          </ul>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-stone-900">6. Intellectual Property</h2>
          <p>
            The AstraMap name, logo, and original source code are owned by the operator.
            AI-generated chart interpretations are provided to you for personal use; you
            may not resell or redistribute them commercially without permission.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-stone-900">7. Disclaimer of Warranties</h2>
          <p>
            AstraMap is provided <strong>"as is"</strong> without warranty of any kind.
            We do not guarantee the accuracy, completeness, or fitness for a particular
            purpose of any chart or interpretation. The service may be interrupted,
            contain errors, or be discontinued at any time without notice.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-stone-900">8. Limitation of Liability</h2>
          <p>
            To the fullest extent permitted by law, AstraMap and its operator shall not
            be liable for any indirect, incidental, special, consequential, or punitive
            damages arising from your use of, or inability to use, the service.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-stone-900">9. Changes to Terms</h2>
          <p>
            We reserve the right to modify these terms at any time. Changes take effect
            upon posting with an updated effective date. Continued use of the service
            after changes constitutes acceptance of the revised terms.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-stone-900">10. Contact</h2>
          <p>
            Questions about these terms? Contact us at{" "}
            <a
              href="mailto:fyuming2@gmail.com"
              className="text-amber-700 underline underline-offset-2 hover:text-amber-900"
            >
              fyuming2@gmail.com
            </a>
            .
          </p>
        </section>
      </div>
    </main>
  );
}
